# -*- coding: utf-8 -*-
"""
Module 3: Retrieval-Augmented Cognitive Router

This module implements the "Retrieval-Guided Meta-Planning" mechanism that
uses retrieved similar cases to guide tool selection.
"""
import os
import json
import re
from dataclasses import dataclass, field
from typing import List, Dict, Optional, Any, Tuple
from enum import Enum

from openai import OpenAI

import sys
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from framework.config import (
    API_BASE_URL, COGNITIVE_TOOLS, AVAILABLE_MODELS, 
    DEFAULT_MODEL, DEFAULT_FRAMEWORK_CONFIG
)
from framework.tools import ToolType, CognitiveToolManager
from framework.knowledge_base import RetrievalResult, KnowledgeBase


@dataclass
class RoutingPlan:
    """Execution plan generated by the router"""
    selected_tools: List[ToolType]
    reasoning: str  # Why these tools were selected
    reference_patterns: List[str]  # Patterns observed in similar cases
    priority_order: List[ToolType]  # Execution priority
    confidence: float = 0.5
    
    def to_dict(self) -> Dict:
        return {
            "selected_tools": [t.value for t in self.selected_tools],
            "reasoning": self.reasoning,
            "reference_patterns": self.reference_patterns,
            "priority_order": [t.value for t in self.priority_order],
            "confidence": self.confidence
        }
    
    def get_tool_list_string(self) -> str:
        return ", ".join([t.value for t in self.selected_tools])


class CognitiveRouter:
    """
    Cognitive Router for intelligent tool selection
    
    Uses retrieved similar cases to determine which cognitive tools
    are most relevant for analyzing the current meme.
    """
    
    def __init__(
        self,
        client: Optional[OpenAI] = None,
        model: str = DEFAULT_MODEL,
        config: Optional[Any] = None
    ):
        if client is None:
            self.client = OpenAI(
                api_key=os.getenv("OPENAI_API_KEY"),
                base_url=API_BASE_URL
            )
        else:
            self.client = client
            
        self.model_config = AVAILABLE_MODELS.get(model, AVAILABLE_MODELS[DEFAULT_MODEL])
        self.config = config or DEFAULT_FRAMEWORK_CONFIG
        
        # Build tool descriptions for the prompt
        self.tool_descriptions = self._build_tool_descriptions()
    
    def _build_tool_descriptions(self) -> str:
        """Build formatted tool descriptions for the router prompt"""
        descriptions = []
        for tool_key, tool_config in COGNITIVE_TOOLS.items():
            descriptions.append(
                f"- **{tool_key}**: {tool_config.name} - {tool_config.description}"
            )
        return "\n".join(descriptions)
    
    def _encode_image(self, image_path: str) -> str:
        """Encode image to base64"""
        import base64
        with open(image_path, "rb") as f:
            return base64.b64encode(f.read()).decode("utf-8")
    
    def _call_llm(
        self,
        prompt: str,
        image_path: Optional[str] = None,
        temperature: float = 0.0,
        max_tokens: int = 1024,
        max_retries: int = 3
    ) -> str:
        """Call LLM with optional image, with retry on connection errors"""
        import time as _time
        
        messages = [{
            "role": "user",
            "content": [{"type": "text", "text": prompt}]
        }]
        
        if image_path and os.path.exists(image_path):
            image_b64 = self._encode_image(image_path)
            messages[0]["content"].append({
                "type": "image_url",
                "image_url": {"url": f"data:image/jpeg;base64,{image_b64}"}
            })
        
        last_error = None
        for attempt in range(1, max_retries + 1):
            try:
                response = self.client.chat.completions.create(
                    model=self.model_config.api_name,
                    messages=messages,
                    temperature=temperature,
                    max_tokens=max_tokens
                )
                return response.choices[0].message.content.strip()
            except Exception as e:
                last_error = e
                if attempt < max_retries:
                    wait = 2 ** attempt
                    print(f"[Router] API call failed (attempt {attempt}/{max_retries}): {e}. Retrying in {wait}s...")
                    _time.sleep(wait)
                else:
                    print(f"[Router] API call failed after {max_retries} attempts: {e}")
        
        return f"Error: {str(last_error)}"
    
    def _parse_tool_selection(self, response: str) -> Tuple[List[ToolType], str, float]:
        """Parse tool selection from LLM response"""
        selected_tools = []
        reasoning = ""
        confidence = 0.5
        
        try:
            # Try to find JSON in response
            json_match = re.search(r'\{.*\}', response, re.DOTALL)
            if json_match:
                data = json.loads(json_match.group())
                
                # Extract selected tools
                tool_names = data.get("selected_tools", [])
                for name in tool_names:
                    try:
                        selected_tools.append(ToolType(name))
                    except ValueError:
                        # Try to match partial names
                        for tt in ToolType:
                            if name.lower() in tt.value.lower() or tt.value.lower() in name.lower():
                                selected_tools.append(tt)
                                break
                
                reasoning = data.get("reasoning", "")
                confidence = float(data.get("confidence", 0.5))
                
        except json.JSONDecodeError:
            # Fallback: try to extract tool names from text
            response_lower = response.lower()
            for tt in ToolType:
                if tt.value.lower() in response_lower:
                    selected_tools.append(tt)
            reasoning = response
        
        # Ensure we have at least min_tools
        if len(selected_tools) < self.config.min_tools_to_select:
            # Add high-priority tools that weren't selected
            priority_tools = [
                ToolType.IMAGE_TEXT_ALIGNER,
                ToolType.SENTIMENT_REVERSAL,
                ToolType.CULTURE_RETRIEVER,
                ToolType.TARGET_IDENTIFIER
            ]
            for pt in priority_tools:
                if pt not in selected_tools and len(selected_tools) < self.config.min_tools_to_select:
                    selected_tools.append(pt)
        
        # Limit to max_tools
        selected_tools = selected_tools[:self.config.max_tools_to_select]
        
        return selected_tools, reasoning, confidence
    
    def _extract_patterns_from_context(self, retrieval_result: RetrievalResult) -> List[str]:
        """Extract common patterns from retrieved examples"""
        patterns = []
        
        for example in retrieval_result.retrieved_examples:
            if example.explanation:
                # Simple pattern extraction from explanations
                patterns.append(example.explanation[:200])
        
        return patterns
    
    def route(
        self,
        image_path: str,
        text: str,
        retrieval_result: Optional[RetrievalResult] = None
    ) -> RoutingPlan:
        """
        Generate routing plan based on meme and retrieved context
        
        Args:
            image_path: Path to meme image
            text: Meme text
            retrieval_result: Retrieved similar examples (optional)
            
        Returns:
            RoutingPlan with selected tools and reasoning
        """
        # Build context from retrieved examples
        context_str = ""
        reference_patterns = []
        
        if retrieval_result and retrieval_result.retrieved_examples:
            context_str = retrieval_result.get_context_string()
            reference_patterns = self._extract_patterns_from_context(retrieval_result)
        
        # Build the routing prompt
        prompt = f'''You are an intelligent router for a meme analysis system. Your task is to select the most relevant cognitive tools to analyze a given meme.

## Available Tools:
{self.tool_descriptions}

## Current Meme:
Text: "{text}"
[Image attached]

## Reference Cases (similar memes from knowledge base):
{context_str if context_str else "No similar cases available."}

## Your Task:
Based on the current meme and patterns observed in similar cases:
1. Analyze what aspects of this meme need investigation
2. Select {self.config.min_tools_to_select}-{self.config.max_tools_to_select} most relevant tools
3. Consider what tools were implicitly needed to analyze the reference cases
4. Prioritize tools based on likely relevance

## Output Format (JSON):
{{
    "analysis": "<brief analysis of what makes this meme potentially harmful/harmless>",
    "patterns_observed": ["<pattern 1 from references>", "<pattern 2>"],
    "selected_tools": ["<tool_key_1>", "<tool_key_2>", ...],
    "tool_justifications": {{
        "<tool_key>": "<why this tool is needed>"
    }},
    "priority_order": ["<most_important_tool>", "<second>", ...],
    "reasoning": "<overall reasoning for tool selection>",
    "confidence": <0.0 to 1.0>
}}

Important:
- Tool keys must be from: {", ".join([t.value for t in ToolType])}
- Select tools based on what information is NEEDED, not what's obviously present
- If similar cases show cultural references matter, include culture_retriever
- If there's apparent text-image mismatch, include image_text_aligner
- Balance between coverage and efficiency'''

        response = self._call_llm(prompt, image_path)
        
        # Parse the response
        selected_tools, reasoning, confidence = self._parse_tool_selection(response)
        
        # Determine priority order (try to extract from response)
        priority_order = selected_tools.copy()
        try:
            json_match = re.search(r'\{.*\}', response, re.DOTALL)
            if json_match:
                data = json.loads(json_match.group())
                if "priority_order" in data:
                    priority_order = []
                    for name in data["priority_order"]:
                        try:
                            priority_order.append(ToolType(name))
                        except:
                            pass
                    # Add any missing tools
                    for tool in selected_tools:
                        if tool not in priority_order:
                            priority_order.append(tool)
        except:
            pass
        
        return RoutingPlan(
            selected_tools=selected_tools,
            reasoning=reasoning,
            reference_patterns=reference_patterns,
            priority_order=priority_order,
            confidence=confidence
        )
    
    def route_simple(
        self,
        image_path: str,
        text: str
    ) -> RoutingPlan:
        """
        Simple routing without retrieval context
        Uses a simpler prompt for efficiency
        """
        prompt = f'''Analyze this meme and select the most relevant analysis tools.

Text: "{text}"
[Image attached]

Available tools:
{self.tool_descriptions}

Select {self.config.min_tools_to_select}-{self.config.max_tools_to_select} tools that would be most useful.

Output as JSON:
{{
    "selected_tools": ["tool_key_1", "tool_key_2", ...],
    "reasoning": "<brief reasoning>",
    "confidence": <0.0-1.0>
}}

Tool keys: {", ".join([t.value for t in ToolType])}'''

        response = self._call_llm(prompt, image_path)
        selected_tools, reasoning, confidence = self._parse_tool_selection(response)
        
        return RoutingPlan(
            selected_tools=selected_tools,
            reasoning=reasoning,
            reference_patterns=[],
            priority_order=selected_tools,
            confidence=confidence
        )
    
    def route_with_rules(
        self,
        image_path: str,
        text: str,
        rules: Optional[str] = None
    ) -> RoutingPlan:
        """
        Route with explicit rules/patterns
        Useful when patterns have been extracted from multiple retrieved examples
        """
        prompt = f'''You are analyzing a meme. Select the appropriate analysis tools.

Text: "{text}"
[Image attached]

Available tools:
{self.tool_descriptions}

{"## Known Patterns/Rules from similar memes:" if rules else ""}
{rules if rules else ""}

Select {self.config.min_tools_to_select}-{self.config.max_tools_to_select} tools.

Output JSON:
{{
    "selected_tools": ["tool_key_1", ...],
    "reasoning": "<reasoning>",
    "confidence": <0.0-1.0>
}}

Valid tool keys: {", ".join([t.value for t in ToolType])}'''

        response = self._call_llm(prompt, image_path)
        selected_tools, reasoning, confidence = self._parse_tool_selection(response)
        
        return RoutingPlan(
            selected_tools=selected_tools,
            reasoning=reasoning if reasoning else "Rule-based routing",
            reference_patterns=[rules] if rules else [],
            priority_order=selected_tools,
            confidence=confidence
        )


class AdaptiveRouter(CognitiveRouter):
    """
    Extended router with adaptive capabilities
    Learns from past routing decisions to improve future selections
    """
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.routing_history: List[Dict] = []
    
    def record_routing_outcome(
        self,
        plan: RoutingPlan,
        was_correct: bool,
        actual_label: int,
        predicted_label: int
    ):
        """Record routing outcome for learning"""
        self.routing_history.append({
            "tools": [t.value for t in plan.selected_tools],
            "reasoning": plan.reasoning,
            "was_correct": was_correct,
            "actual": actual_label,
            "predicted": predicted_label
        })
    
    def get_tool_effectiveness_stats(self) -> Dict[str, Dict]:
        """Calculate effectiveness statistics for each tool"""
        tool_stats = {t.value: {"used": 0, "correct": 0} for t in ToolType}
        
        for record in self.routing_history:
            for tool in record["tools"]:
                if tool in tool_stats:
                    tool_stats[tool]["used"] += 1
                    if record["was_correct"]:
                        tool_stats[tool]["correct"] += 1
        
        # Calculate accuracy
        for tool, stats in tool_stats.items():
            if stats["used"] > 0:
                stats["accuracy"] = stats["correct"] / stats["used"]
            else:
                stats["accuracy"] = None
        
        return tool_stats


if __name__ == "__main__":
    # Test the router
    router = CognitiveRouter()
    
    test_image = "data/FHM/images/16395.png"
    test_text = "handjobs sold seperately"
    
    if os.path.exists(test_image):
        print("Testing router...")
        
        # Test simple routing
        plan = router.route_simple(test_image, test_text)
        print(f"\nSelected tools: {plan.get_tool_list_string()}")
        print(f"Reasoning: {plan.reasoning}")
        print(f"Confidence: {plan.confidence}")
    else:
        print(f"Test image not found: {test_image}")
